### ISSUE TITLE
Resources not appearing on permission box

### ISSUE THREAD

**Issue by mavrickdeveloper** [hexters/hexa-lite#2]
Hi there , just wanted to ask if  you have an idea why my resources are not visible on the permissions select box
only default ones appears

![Screenshot 2024-09-12 132756](https://github.com/user-attachments/assets/f41a809a-f3b1-4f2c-a5de-d73382ff04fc)

**Comment by hexters** [comment]
Since your role is superadmin, superadmins are not allowed to change the main permissions.
