### ISSUE TITLE
I can't find the  Hexters\HexaLite\Pages\Option class in the package 

### ISSUE THREAD

**Issue by horaciod** [hexters/hexa-lite#3]
https://github.com/hexters/hexa-lite/blob/93d2424165db9d21c0105199db229f4e7cf48154/stubs/Filament/Pages/Option.php#L7

**Comment by horaciod** [comment]
without this is impossible to access to form options .

**Comment by hexters** [comment]
Thanks for reminding, I will delete the file later.

And this option can only be accessed on Hexa Pro you can get it here. [Hexa Filament](https://github.com/hexters/hexa-docs)
